# Generated by Django 3.2.2 on 2021-06-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applicant_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='data_cadastro',
            field=models.DateField(),
        ),
    ]
