# Generated by Django 3.2.2 on 2021-06-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210608_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título')),
                ('req', models.TextField(verbose_name='Requisitos')),
                ('faixa_salarial', models.CharField(choices=[('1000', 'Até R$ 1000'), ('1000 - 2000', 'De R$ 1000 a R$ 2000'), ('2000 - 3000', 'De R$ 2000 a R$ 3000'), ('3000', 'Acima de R$ 3000')], default='1000', max_length=20, verbose_name='Faixa Salarial')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino fundamental'), ('medio', 'Ensino médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Ensino Superior'), ('pos', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], max_length=20, verbose_name='Escolaridade Mínima')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Empresa')),
            ],
        ),
    ]
