# Generated by Django 3.2.2 on 2021-06-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210608_1844'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(verbose_name='Pontos do Candidato')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicant')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancies')),
            ],
        ),
    ]
