# Generated by Django 3.2.2 on 2021-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacanciesapplications_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesapplications',
            name='pontos',
            field=models.PositiveIntegerField(verbose_name='Pontos do Candidato'),
        ),
    ]
