# Generated by Django 3.2.2 on 2021-06-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacanciesapplications_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanciesapplications',
            name='pontos',
        ),
    ]
