# Generated by Django 3.2.2 on 2021-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_vacanciesapplications_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacanciesapplications',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
