# Generated by Django 3.2.2 on 2021-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_rename_data_vacanciesapplications_data_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanciesapplications',
            name='pontos_candidato',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos do Candidato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacanciesapplications',
            name='data_inscricao',
            field=models.DateField(auto_now=True, verbose_name='Data de Inscrição'),
        ),
    ]
