# Generated by Django 3.2.2 on 2021-06-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_auto_20210611_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Vacancie', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacanciesapplications',
            options={'verbose_name': 'Vacancies Application', 'verbose_name_plural': 'Vacancies Applications'},
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='data_criacao',
            field=models.DateField(),
        ),
    ]
