# Generated by Django 3.2.2 on 2021-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20210611_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacanciesapplications',
            name='data_inscricao',
            field=models.DateField(verbose_name='Data de Inscrição'),
        ),
    ]
