# Generated by Django 3.2.2 on 2021-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20210611_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacanciesapplications',
            name='data_inscricao',
            field=models.DateField(auto_now=True, verbose_name='Data de Inscrição'),
        ),
    ]
