# Generated by Django 3.2.2 on 2021-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20210611_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='data_criacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Criação'),
        ),
    ]
